### ISSUE TITLE
Faulty Permit2 remappings due to lack of context-aware remappings in Foundry

### ISSUE THREAD

**Issue by andreivladbrg** [sablier-labs/v2-periphery#136]
In the latest [PR](https://github.com/sablier-labs/v2-periphery/pull/131) we added re-export types. However, this does not work for `permit2` due to the remappings we declared:

https://github.com/sablier-labs/v2-periphery/blob/76c5af55739c0447bff956ea6287be3ae8e8c22a/remappings.txt#L9-L10

When attempting to import the `permit2` types from `v2-periphery`, the following error will appears:

![image](https://github.com/sablier-labs/v2-periphery/assets/99738872/4438835e-0e5d-4017-95af-6d6e999c1d50)

The solution to this issue involves changing the remappings to:
```
@permit2/=lib/permit2/src/
@permit2-test/=lib/permit2/test/
```

**Comment by PaulRBerg** [comment]
Good catch.

> In the latest https://github.com/sablier-labs/v2-periphery/pull/131 we added re-export types.

Red herring because this problem existed even before the re-exports PR. That is, `IAllowanceTransfer` can't be imported directly from `@sablier/v2-periphery`, with or without the `Permit2.sol` re-exports.

>  this does not work for permit2 due to the remappings we declared:

Another red herring - the issue is not due to our remappings but due to a bug in Foundry (or more than just one bug):

- https://github.com/foundry-rs/foundry/issues/1855
- https://github.com/foundry-rs/foundry/issues/3440
- https://github.com/foundry-rs/foundry/issues/4108

Interestingly, Uniswap stumbled upon the same problem, and they ended up changing the absolute imports to relative imports (add `/src/` in the paths):

https://github.com/Uniswap/permit2/pull/160/files

Unfortunately, that would lead to a massive refactor for us. A critical difference is that in our case, we are using remappings in production code.

> The solution to this issue involves changing the remappings to:

If we do this, I'd change them to `@uniswap/permit2`.

**Comment by PaulRBerg** [comment]
I have made up my mind about this - let's refactor the `permit2` remapping to `@uniswap/permit2`.

Even if Foundry adds support for context-aware remappings shortly, there will remain the long tail of users who will not run `foundryup` anytime soon.

@andreivladbrg - could you handle this task, please?

**Comment by andreivladbrg** [comment]
On it rn

**Comment by PaulRBerg** [comment]
> Not sure what you mean, isn't it already @uniswap/permit2?

Shoot - you're right! This only has to be done for the Foundry remapping.
