### ISSUE TITLE
Write differential tests for airstreams

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#175]
The [airstreams](https://github.com/sablier-labs/v2-periphery/pull/174) are a prime candidate for [differential testing](https://book.getfoundry.sh/forge/differential-ffi-testing?highlight=merkle#example-differential-testing-merkle-tree-implementations).

The idea is to check that the Merkle proofs generated by an off-chain library such as the [one written by OpenZeppelin](https://github.com/OpenZeppelin/merkle-tree#validating-a-proof-in-solidity) is compatible with our on-chain implementation.

**Comment by andreivladbrg** [comment]
I am not sure what we need to test since everything related to merkle trees is used from an external source.

Can you explain what should be tested and why is this necessary given:
 - we use OpenZeppelin's library to verify a claim, which is already [tested in JS](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/test/utils/cryptography/MerkleProof.test.js). 
 - we use murky's library to generate the root and the merkle proofs in our tests, which already has [differential tests](https://github.com/dmfxyz/murky/tree/main/differential_testing/).

**Comment by PaulRBerg** [comment]
Yeah, good point. I agree with you now. Not worth it to do this at the moment.

However, it might be worth it to consider if invariant tests would help.
