### ISSUE TITLE
Fix logical inconsistency in "claim" tests

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#196]
Context: https://github.com/alexfertel/bulloak/discussions/7#discussioncomment-7132221

**Comment by andreivladbrg** [comment]
I want to make sure, you are suggesting to change this:
```
      ├── given the claim is not included in the Merkle tree
      │  ├── when the index is not valid
      │  │  └── it should revert
      │  ├── when the recipient address is not valid
      │  │  └── it should revert
      │  ├── when the amount is not valid
      │  │  └── it should revert
      │  └── when the Merkle proof is not valid
      │     └── it should revert
      └── given the claim is included in the Merkle tree
```

to this:

```
      ├── given the claim is not included in the Merkle tree
      │  ├── when the index is not valid
      │  │  └── it should revert
      │  └── when the index is valid
      │      ├── when the recipient address is not valid
      │      │  └── it should revert
      │      └── when the recipient address is valid
      │          ├── when the amount is not valid
      │          │  └── it should revert
      │          └── when the amount is valid
      │              └── when the Merkle proof is not valid
      │                 └── it should revert
      └── given the claim is included in the Merkle tree
```

Am I right?

**Comment by andreivladbrg** [comment]
> [test_RevertWhen_InvalidMerkleProof](https://github.com/sablier-labs/v2-periphery/blob/c1acdfe9dd63e903a639de04727b64ffacd7da22/test/integration/merkle-streamer/ll/claim/claim.t.sol#L87) test and its associated branch because it does not make logical sense.

It is not clear to me why a parameter, index recipient or amount, should have an associated branch but the `merkleProof` should not. If we remove this branch, there would be an unit test that is not covered(might reduce the coverage).

https://github.com/sablier-labs/v2-periphery/blob/c1acdfe9dd63e903a639de04727b64ffacd7da22/src/interfaces/ISablierV2MerkleStreamerLL.sol#L34-L44

By Merkle proof is valid, we mean that the array of `bytes32` is actually the correct array for corresponding node (node = `hash(index,recipient,amount)`). See here, we pass second's proof to first index: 

https://github.com/sablier-labs/v2-periphery/blob/c1acdfe9dd63e903a639de04727b64ffacd7da22/test/integration/merkle-streamer/ll/claim/claim.t.sol#L93-L95

> The claim being not included in the Merkle tree = the Merkle proof is invalid

This statement is correct, but so is for index recipient or amount: 
- The claim being not included in the Merkle tree = index is invalid
- The claim being not included in the Merkle tree = recipient is invalid
- The claim being not included in the Merkle tree = amount is invalid

I think we are facing an issue here because the terminology used is a little bit confusing. 

Given a 4 nodes merkle tree:

claim is included in the Merkle tree => $merkle root = hash(hash( hash(data),first level node), second level node)$

hash(data) = hash(index,recipient,amount)
first level node + second level node = `merkleProof` array

<img width="500" alt="image" src="https://github.com/sablier-labs/v2-periphery/assets/99738872/9051f855-8cd9-4106-a2f6-e9c613346b49">

> A proof is invalid because of some particular reason, such as the recipient's address or the amount being invalid. This is why the other branches are ok.

A particular reason can also be that one of the level nodes is not the correct node.

Having said that, we _should not_ remove this branch.

**Comment by PaulRBerg** [comment]
Thanks for the detailed explanation, @andreivladbrg. There was a misconception on my part, namely, that I did not consider the possibility of a correct `(index,recipient,amount)` pair but an incorrect intermediary path in the Merkle tree.

However, this makes me realize that the terminology can and should be improved. "not valid" is vague.

I've asked ChatGPT how these intermediary hashes are called, and it turns out that their name is [interior nodes](https://chat.openai.com/share/56b79764-2663-41c5-9960-7fa30e5ef7f3).

Thus, how about we rename the branch to "when the interior nodes are not valid"?

**Comment by andreivladbrg** [comment]
> Thus, how about we rename the branch to "when the interior nodes are not valid"?

which branch are you referring to?

https://github.com/sablier-labs/v2-periphery/blob/7b397cf9146bfe72edadf93c760fdb513d3d6ee9/test/integration/merkle-streamer/ll/claim/claim.tree#L8-L17

Do you mean like this? 

```diff
- ├── given the claim is not included in the Merkle tree
+ ├── when the interior nodes are not valid
// --snip--
- └── given the claim is included in the Merkle tree
+ ├── when the interior nodes are valid
``` 

It would work for me, but let's say "when the interior nodes _in the Merkle tree_ are not valid" for being more specific

**Comment by PaulRBerg** [comment]
I'm fine with adding the "in the Merkle tree" qualifier.

This is what I mean:

```diff
- when the Merkle proof is not valid 
+ when the interior nodes in the Merkle tree are not valid
```

**Comment by andreivladbrg** [comment]
> This is what I mean:
when the interior nodes in the Merkle tree are not valid

Oh, I see. I don't think is better like this.

I suggest: "when the Merkle proof's interior nodes are not valid"

**Comment by andreivladbrg** [comment]
yep
