### ISSUE TITLE
Upgrade to OpenZeppelin v5

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#211]
Just like https://github.com/sablier-labs/v2-core/issues/702 and https://github.com/sablier-labs/v2-core/pull/703.

This should be implemented on a new `2.2` branch.

**Comment by andreivladbrg** [comment]
There is an issue here with upgrading to v5. We have installed uniswap's version of permit2:

https://github.com/sablier-labs/v2-periphery/blob/51f3c0f0973eb5d038f21ebeb32709ac433fa7fa/.gitmodules#L9-L12

Which is using an [older version](https://github.com/OpenZeppelin/openzeppelin-contracts/tree/d3ff81b37f3c773b44dcaf5fda212c7176eef0e2) of openzeppelin. 

They are installing it because they use various utils from them, as:

https://github.com/Uniswap/permit2/blob/cc56ad0f3439c502c246fc5cfcc3db92bb8b7219/test/utils/PermitSignature.sol#L5

This path needs to be updated to: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/release-v5.0/contracts/utils/cryptography/EIP712.sol

Otherwise it would revert:

<img width="1145" alt="image" src="https://github.com/sablier-labs/v2-periphery/assets/99738872/a836141b-5b24-4bae-a27e-6c95416f546e">

Given how much has taken them to merge the `package.json` PR, should we make the update to v5 in `sablier-labs/permit2` and switch back to it?

**Comment by PaulRBerg** [comment]
Did I mention that I [remappings are a mess](https://twitter.com/PaulRBerg/status/1683153492557348867)?

It is possible to make it work by adding this remapping:

```text
openzeppelin-contracts/=lib/permit2/lib/openzeppelin-contracts/
```

But it's ugly and I would rather not tether our OZ remapping to Permit2's installation.

So yeah let's fork Permit2 again and install OZ v5 in our fork.

**Comment by andreivladbrg** [comment]
Comming back here because I just found out that [these](https://github.com/Uniswap/permit2/blob/cc56ad0f3439c502c246fc5cfcc3db92bb8b7219/test/utils/PermitSignature.sol#L5-L6) imports are not even used 😅

**Comment by PaulRBerg** [comment]
lol

@andreivladbrg you should definitely open a GitHub issue in Uniswap's repo (or even a PR) and let them know why it would be helpful to remove those unused imports

**Comment by andreivladbrg** [comment]
> you should definitely open a GitHub issue in Uniswap's repo (or even a PR) and let them know why it would be helpful to remove those unused imports

Will do in the future. For us, it would still be the better choice to change to `sablier-labs/permit2`

**Comment by smol-ninja** [comment]
Resolved in https://github.com/sablier-labs/v2-periphery/commit/77a0982cb137118d2abc8bd5e43eab143e8c7dfa.
