### ISSUE TITLE
Use precompiles to write a protocol deployment script

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/v2-periphery#238]
Write a deployment script that uses the V2 Core precompiles to deploy the entire Sablier V2 protocol (V2 Core + V2 Periphery).

This is possible to do now because the precompiles are part of the [`@sablier/v2-core`](https://www.npmjs.com/package/@sablier/v2-core?activeTab=code) npm package (in the `test/utils` package).

Note: there is an appearance of misuse by importing production code from `test/utils.` As explained [here](https://github.com/sablier-labs/v2-core/discussions/662), we should consider moving the precompiles - perhaps in `script`, or in `artifacts`, or in `src.

Related: https://github.com/sablier-labs/v2-periphery/pull/91#issuecomment-1580391265

**Comment by andreivladbrg** [comment]
> perhaps in script, or in artifacts, or in `src.

in `script` makes the most sense

**Comment by PaulRBerg** [comment]
Then, we need to include `script` in the npm package.

**Comment by andreivladbrg** [comment]
i think it would be unnecessary to include all `script` dir, we should include only that specific deployment script

**Comment by PaulRBerg** [comment]
Yep, that's what I was referring to.

**Comment by smol-ninja** [comment]
@PaulRBerg, a script to deploy the entire V2 protocol does not make sense because it exceeds the EVM gas limit. As discussed [here](https://github.com/sablier-labs/v2-periphery/pull/302#issue-2177251858), the gas usage of this script is ~100M which is not feasible in production.

For the purpose of testing, we have [added a function](https://github.com/sablier-labs/v2-periphery/blob/1f5e45697eb62e180ff132101ce5f45ed5af80c8/precompiles/Precompiles.sol#L68C1-L84C6) in periphery precompiles that can be used to deploy code + periphery.

**Comment by PaulRBerg** [comment]
Oh, I didn't take the EVM gas limit into consideration when I created this issue.

Closing this, it's an obvious conclusion.

> For the purpose of testing, we have added a function

Good stuff
